require 'digest/sha1'
require 'ipaddr'
require 'rss/2.0'
require 'open-uri'

require 'andand/andand'
require 'weppos/url_validation'
require 'digitpaint/unique_identifiers'
require 'digitpaint/configure'
require 'digitpaint/nested_attributes_positioning'