require 'personify'
require "polyglot"
require "sprockets"
require "mime/types"
require "RMagick"
require 'nokogiri'
require "guid"
require "will_paginate"
require "seed-fu"
require 'mail'
require 'omniauth'